# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# For more details on how to configure your build environment visit
# https://www.gradle.org/configure-gradle-for-your-environment

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include resources from the
# dependencies, thereby reducing the size of the R class in the final APK.
android.nonTransitiveRClass=true

# Enable AndroidX
android.useAndroidX=true

# Enable Jetifier
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# Configuraciones para evitar problemas de jlink
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
android.enableR8.fullMode=false

# Deshabilitar transformaciones JDK problemáticas
android.enableJetifier=true
android.useAndroidX=true
